version: '3.7'

volumes:
  postgres_data:
    driver: local
  pgadmin:

services:
  cabir-api:
    container_name: cabir-api
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
      
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_SSL}:443
    volumes:
      - "./Docker/gateway/templates/:/etc/nginx/templates/"
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.templates"
    depends_on:
      - keycloak

  redis:
    image: redis
    command: redis-server --requirepass cabir --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:cabir
    ports:
      - "8081:8081"
    depends_on:
        - redis

  postgres:
    image: 'postgres'
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./Docker/postgressql/init/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    restart: 'always'
    environment:
      POSTGRES_USER: cabir
      POSTGRES_PASSWORD: cabir
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    volumes:
      - ./Docker/keycloak/migration:/opt/jboss/keycloak/imports
    command:
      - "start-dev"
    environment:
      #KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_ADDR: postgres
      DB_VENDOR: POSTGRES
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_SCHEMA: keycloak
      DB_USER: cabir
      DB_PASSWORD: cabir
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - postgres

